version: 1.0.{build}
branches:
  only:
  - master
  - dev

image: Visual Studio 2017

configuration:
- Release
- Debug

cache:
- build/lib -> appveyor.yml

before_build:
- cmd: >-
    git submodule update --init --recursive
    
    if not exist build\ mkdir build
    cd build
    
    cmake -G "Visual Studio 15 2017 Win64" ../
    
build:
  project: build/HEROES.vcxproj
  parallel: true
  verbosity: minimal
  
after_build:
- cmd: >-
    7z a Heroes_Journey_%CONFIGURATION%_win64.zip %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/Astral_Insanity_main.exe %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/*.dll  %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/**/*
    
    cd ../build/installer/
    
    dir
    
    for %%a in (*.exe) do ren "%%~a" "%%~na_%CONFIGURATION%_win64%%~xa"
    
    dir

test: off
    
artifacts:
  - path: build/*.zip
    name: Heroes_Journey_zip
